### ISSUE TITLE
Using plugin in LightTable 0.6.7

### ISSUE THREAD

**Issue by ghost** [Gozala/LightTable-osx-skin#3]
Hi - This is great!

I've been having trouble activating this in LightTable 0.6.7. Putting the plugin into ~/Library/Application Support/LightTable/plugins doesn't seem to have any effect. This happens when both installing it manually and through LightTable's plugin manager.

The only clue is after is the plugin name appears in red in plugin manager, however looking through the code here, I can't seem to find a reason why it would be unusable/outdated.

Hope you could shed some light on this, Cheers!

**Comment by ghost** [comment]
Ok, I figured it out.

May I suggest adding a line to the documentation saying to set:  
`:app [(:lt.objs.style/set-skin "osx")]`
in the user.behaviors file? I think that would help out a lot of people.

Thanks!

**Comment by Gozala** [comment]
@PandaKun I'm sorry you had trouble getting it to work. I think adding info in the readme would be great suggestion. Wanna send a pull request ?
