### ISSUE TITLE
This doesn't seem to work in LightTable 0.7.0

### ISSUE THREAD

**Issue by seancorfield** [Gozala/LightTable-osx-skin#4]
My (updated-for-0.7.0) `user.behaviors` has:

```
[:app :lt.objs.style/set-skin "osx"]
```

But this doesn't seem to do anything. Per Joshua on IRC:

"Skins are a gray area right now. If they're still trying to use CSS variables they won't work anymore since they've been removed from node-webkit (we've switched to stylus)"

**Comment by mapuo** [comment]
+1

**Comment by mapuo** [comment]
After the update to 0.7.2 the skin is applied and it is looking good.
